### ISSUE TITLE
Can't set a colour

### ISSUE THREAD

**Issue by maheshbansod** [Shizcow/dmenu-rs#51]
Tried the command:
`echo -e "one\ntwo\nthree\nfour\nfive\n" | dmenu --bottom --nf "#F0F"`

Got:
```
thread 'main' panicked at 'source slice length (5) does not match destination slice length (8)', build/../dmenu/clapflags.rs:115:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/core/src/panicking.rs:67:14
   2: core::slice::<impl [T]>::copy_from_slice::len_mismatch_fail
             at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/core/src/slice/mod.rs:3603:13
   3: dmenu::clapflags::validate
   4: dmenu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Expected:
A dmenu at the bottom with foreground colour as specified by the hex code `#FOF`

**Comment by Shizcow** [comment]
Once #52 is merged I'll bump the version and publish a new release so downstream gets these bug-fixes.
